-- Dokument-Anhänge zu Stammdaten (alt: CDisplayFieldDocumentBean).
-- Neu: zentrale, polymorphe Tabelle in PostgreSQL, damit Inhalte zusammen mit den
-- Fachdaten gesichert/restauriert werden können (siehe MIGRATION.md / Backup-Strategie).

CREATE TABLE frauenhaus.dokument (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_typ       varchar(20)  NOT NULL CHECK (entity_typ IN ('MITGLIED', 'VEREIN', 'BUSSGELD', 'SPENDE', 'GERICHT')),
    entity_id        varchar(100) NOT NULL,
    dateiname        varchar(255) NOT NULL,
    content_type     varchar(150) NOT NULL,
    groesse          bigint       NOT NULL CHECK (groesse >= 0),
    inhalt           bytea        NOT NULL,
    hochgeladen_am   timestamptz  NOT NULL DEFAULT now(),
    hochgeladen_von  varchar(50)  NOT NULL
);

CREATE INDEX idx_dokument_entity ON frauenhaus.dokument (entity_typ, entity_id);
