-- Baseline: abgeglichen mit dem MSSQL-Backup des Altsystems (Backup_MSSQL_FH_anonymisiert.bak).
-- Fachschema "frauenhaus" – die compucrash.*-Metatabellen (object_def, button_def, ...)
-- steuerten die alte Swing-UI und werden bewusst NICHT übernommen.

CREATE SCHEMA IF NOT EXISTS frauenhaus;

-- Lookup: Anreden (alt: frauenhaus.anrede)
CREATE TABLE frauenhaus.anrede (
    anrede varchar(50) PRIMARY KEY
);

-- Träger (alt: frauenhaus.verein; feste Werte 'Frauenhaus' und 'Förderverein')
CREATE TABLE frauenhaus.verein (
    verein      varchar(50)  PRIMARY KEY,
    bezeichnung varchar(200) NOT NULL
);

INSERT INTO frauenhaus.verein (verein, bezeichnung) VALUES
    ('Frauenhaus',   'Frauenhaus'),
    ('Förderverein', 'Förderverein');

-- Mitglieder / Adressen (alt: frauenhaus.mitglied)
CREATE TABLE frauenhaus.mitglied (
    mitglied      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anrede        varchar(50) REFERENCES frauenhaus.anrede (anrede),
    vorname       varchar(100),
    name          varchar(100) NOT NULL,
    name2         varchar(100),
    name3         varchar(100),
    briefanrede   varchar(200),
    strasse       varchar(200),
    plz           varchar(10),
    ort           varchar(100),
    email         varchar(200),
    tel1          varchar(50),
    tel2          varchar(50),
    fax           varchar(50),
    foerderverein boolean NOT NULL DEFAULT false,  -- Mitglied im Förderverein
    frauenhaus    boolean NOT NULL DEFAULT false,  -- Mitglied im Frauenhaus-Verein
    bemerkung     text
);

-- m:n Mitglied <-> Verein (alt: frauenhaus.verein_mitglied)
CREATE TABLE frauenhaus.verein_mitglied (
    verein   varchar(50) NOT NULL REFERENCES frauenhaus.verein (verein),
    mitglied bigint      NOT NULL REFERENCES frauenhaus.mitglied (mitglied) ON DELETE CASCADE,
    PRIMARY KEY (verein, mitglied)
);

-- Lookup: Spendentypen (alt: eigene Tabelle frauenhaus.spendentyp,
-- bekannte Werte u.a. 'Geldspende dauer', 'Mitgliedsbeitrag', 'Dauerspende', 'Sachspende')
CREATE TABLE frauenhaus.spendentyp (
    spendentyp varchar(100) PRIMARY KEY
);

CREATE TABLE frauenhaus.spendenart (
    spendenart varchar(100) PRIMARY KEY,
    spendentyp varchar(100) NOT NULL REFERENCES frauenhaus.spendentyp (spendentyp)
);

CREATE TABLE frauenhaus.spende (
    spende     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mitglied   bigint        NOT NULL REFERENCES frauenhaus.mitglied (mitglied),
    spendenart varchar(100)  NOT NULL REFERENCES frauenhaus.spendenart (spendenart),
    verein     varchar(50)   NOT NULL REFERENCES frauenhaus.verein (verein),
    datum      date          NOT NULL,
    betrag     numeric(12,2) NOT NULL CHECK (betrag >= 0),
    bemerkung  text
);
CREATE INDEX idx_spende_mitglied ON frauenhaus.spende (mitglied);
CREATE INDEX idx_spende_datum    ON frauenhaus.spende (datum);

CREATE TABLE frauenhaus.gericht (
    gericht     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bezeichnung varchar(200) NOT NULL,
    strasse     varchar(200),
    plz         varchar(10),
    ort         varchar(100)
);

CREATE TABLE frauenhaus.bussgeldstatus (
    bussgeldstatus varchar(50) PRIMARY KEY
);

CREATE TABLE frauenhaus.bussgeld (
    bussgeld     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gericht      bigint        NOT NULL REFERENCES frauenhaus.gericht (gericht),
    verein       varchar(50)   NOT NULL REFERENCES frauenhaus.verein (verein),
    status       varchar(50)   REFERENCES frauenhaus.bussgeldstatus (bussgeldstatus),
    name         varchar(100),
    vorname      varchar(100),
    aktenzeichen varchar(100),
    datum        date          NOT NULL,
    zieldatum    date,                              -- Zahlungsziel
    betrag       numeric(12,2) NOT NULL CHECK (betrag >= 0),
    bezahlt      boolean NOT NULL DEFAULT false,
    bemerkung    text
);
CREATE INDEX idx_bussgeld_gericht ON frauenhaus.bussgeld (gericht);
CREATE INDEX idx_bussgeld_datum   ON frauenhaus.bussgeld (datum);

-- Zahlungseingänge zu Bußgeldern (alt: frauenhaus.eingang)
CREATE TABLE frauenhaus.eingang (
    eingang   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bussgeld  bigint        NOT NULL REFERENCES frauenhaus.bussgeld (bussgeld) ON DELETE CASCADE,
    datum     date          NOT NULL,
    betrag    numeric(12,2) NOT NULL,
    bemerkung text
);
CREATE INDEX idx_eingang_bussgeld ON frauenhaus.eingang (bussgeld);

-- Stichworte / Verteiler (alt: frauenhaus.stichwort, frauenhaus.stichwort_person)
CREATE TABLE frauenhaus.stichwort (
    stichwort varchar(100) PRIMARY KEY
);

CREATE TABLE frauenhaus.stichwort_person (
    stichwort varchar(100) NOT NULL REFERENCES frauenhaus.stichwort (stichwort) ON DELETE CASCADE,
    mitglied  bigint       NOT NULL REFERENCES frauenhaus.mitglied (mitglied)  ON DELETE CASCADE,
    PRIMARY KEY (stichwort, mitglied)
);
CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE app.app_user (
                              id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              username      varchar(50)  NOT NULL UNIQUE,
                              password_hash varchar(100) NOT NULL,
                              role          varchar(30)  NOT NULL CHECK (role IN ('ADMIN', 'SACHBEARBEITUNG')),
                              enabled       boolean      NOT NULL DEFAULT true,
                              created_at    timestamptz  NOT NULL DEFAULT now()
);

